name: Push to Hugging Face Space
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with full history and LFS
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.email "pavancs325@email.com"
          git config --global user.name "csparthasarathy"

      - name: Install and configure Git LFS
        run: |
          git lfs install
          git lfs track "*.pkl"
          git add .gitattributes
          git add data_vec.pkl # Ensure data_vec.pkl is added AFTER tracking

      - name: Commit changes
        run: |
          git diff --staged --quiet || git commit -m "Configure Git LFS and add data_vec.pkl"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://pavancs:${HF_TOKEN}@huggingface.co/spaces/pavancs/newapp
          git push space main --force
