name: Push to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true   # Enable LFS for this checkout

      - name: Set up Git LFS
        run: |
          git lfs install
          git lfs track "*.pkl"
          git add .gitattributes
          git add data_vec.pkl
          git commit -m "Track .pkl with LFS" || echo "Nothing to commit"

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "your@email.com"
          git config --global user.name "Your Name"
          git remote add space https://pavancs:${HF_TOKEN}@huggingface.co/spaces/pavancs/newapp
          git push space main --force
